export default [
  {
    adult: false,
    imgURL: "/vjnLXptqdxnpNJer5fWgj2OIGhL.jpg",
    genre_ids: [28, 53, 80],
    id: 818397,
    original_language: "en",
    original_title: "Memory",
    overview:
      "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
    popularity: 854.139,
    poster_path: "/4Q1n3TwieoULnuaztu9aFjqHDTI.jpg",
    release_date: "2022-04-28",
    title: "Memory",
    video: false,
    vote_average: 7.3,
    vote_count: 687,
  },
  {
    adult: false,
    imgURL: "/wUwizGzbTk5CTiKBnE4Pq1MONwD.jpg",
    genre_ids: [16, 12, 10751, 14],
    id: 560057,
    original_language: "en",
    original_title: "The Sea Beast",
    overview:
      "The life of a legendary sea monster hunter is turned upside down when a young girl stows away on his ship.",
    popularity: 785.867,
    poster_path: "/9Zfv4Ap1e8eKOYnZPtYaWhLkk0d.jpg",
    release_date: "2022-06-24",
    title: "The Sea Beast",
    video: false,
    vote_average: 7.7,
    vote_count: 640,
  },
  {
    adult: false,
    imgURL: "/8TUb2U9GN3PonbXAQ1FBcJ4XeXu.jpg",
    genre_ids: [53, 27],
    id: 760741,
    original_language: "en",
    original_title: "Beast",
    overview:
      "A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
    popularity: 766.511,
    poster_path: "/xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg",
    release_date: "2022-08-11",
    title: "Beast",
    video: false,
    vote_average: 6.9,
    vote_count: 15,
  },
  {
    adult: false,
    imgURL: "/cugmVwK0N4aAcLibelKN5jWDXSx.jpg",
    genre_ids: [16, 28, 12, 878],
    id: 768744,
    original_language: "ja",
    original_title: "僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション",
    overview:
      "A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-classic selected hero team. It is up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academia.",
    popularity: 556.381,
    poster_path: "/AsTlA7dj2ySGY1pzGSD0MoHFhEF.jpg",
    release_date: "2021-08-06",
    title: "My Hero Academia: World Heroes' Mission",
    video: false,
    vote_average: 7.6,
    vote_count: 251,
  },
  {
    adult: false,
    imgURL: "/dFCtmk760k1j6G0sSPrZMnMuNuL.jpg",
    genre_ids: [27, 53, 28],
    id: 960258,
    original_language: "en",
    original_title: "Shark Bait",
    overview:
      "A group of friends enjoying a weekend steal a couple of jetskis racing them out to sea, ending up in a horrific head-on collision. They struggle to find a way home with a badly injured friend while from the waters below predators lurk.",
    popularity: 534.244,
    poster_path: "/mVVU9zC8snNHlcqYONY2HOsh9ob.jpg",
    release_date: "2022-05-13",
    title: "Shark Bait",
    video: false,
    vote_average: 6.2,
    vote_count: 114,
  },
  {
    adult: false,
    imgURL: "/tzNx4y7kYf1Xw3F3T6QxrE7PPwb.jpg",
    genre_ids: [53, 18, 80, 9648, 27],
    id: 825808,
    original_language: "en",
    original_title: "See for Me",
    overview:
      "When blind former skier Sophie cat-sits in a secluded mansion, three thieves invade for the hidden safe. Sophie's only defense is army veteran Kelly, who she meets on the See For Me app. Kelly helps Sophie defend herself against the invaders and survive.",
    popularity: 475.037,
    poster_path: "/qk1ZERG6yhwAJqTobmDgw8jRL2C.jpg",
    release_date: "2022-01-07",
    title: "See for Me",
    video: false,
    vote_average: 6.1,
    vote_count: 97,
  },
  {
    adult: false,
    imgURL: "/54PmeEzQMvpojpJBku61ZGQnWUX.jpg",
    genre_ids: [16, 12, 28, 14],
    id: 900667,
    original_language: "ja",
    original_title: "ONE PIECE FILM RED",
    overview:
      "Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as “otherworldly.” She will appear in public for the first time at a live concert. As the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound. The story begins with the shocking fact that she is \"Shanks' daughter.”",
    popularity: 508.418,
    poster_path: "/gpzMYQQrDLSihHmCLHAKT8h30Oc.jpg",
    release_date: "2022-08-06",
    title: "One Piece Film: Red",
    video: false,
    vote_average: 7.5,
    vote_count: 48,
  },
  {
    adult: false,
    imgURL: "/7ef3yg5eCE6ZGKMsqUrfH8KdSMA.jpg",
    genre_ids: [16, 28, 10751, 878, 35],
    id: 539681,
    original_language: "en",
    original_title: "DC League of Super-Pets",
    overview:
      "When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.",
    popularity: 465.014,
    poster_path: "/r7XifzvtezNt31ypvsmb6Oqxw49.jpg",
    release_date: "2022-07-27",
    title: "DC League of Super-Pets",
    video: false,
    vote_average: 7.3,
    vote_count: 82,
  },
  {
    adult: false,
    imgURL: "/egS5SHI4Ppwmb65lUjqsy79ASnN.jpg",
    genre_ids: [27],
    id: 756681,
    original_language: "es",
    original_title: "Veneciafrenia",
    overview:
      "A group of spanish tourists in Venice finds themselves fighting for their lives against locals that are not too keen on foreigners.",
    popularity: 413.634,
    poster_path: "/luMC56bwZqaECYRz6X7sXjqN6nd.jpg",
    release_date: "2022-04-22",
    title: "Veneciafrenia",
    video: false,
    vote_average: 6.1,
    vote_count: 106,
  },
  {
    adult: false,
    imgURL: "/sahdgvn0Brw6AgdwyLHgdCAynWG.jpg",
    genre_ids: [12, 16, 35, 10751, 14],
    id: 778855,
    original_language: "en",
    original_title: "Chickenhare and the Hamster of Darkness",
    overview:
      "Young Chickenhare is the adopted son of King Peter, a famous adventurer. Part chicken and part hare, he has a really tough time growing up and disguises himself as a hare to avoid the mockeries of his peers. When the day of the Royal Adventurer Society trials comes, Chickenhare, hampered by his disguise, fails miserably. But he is determined to grab a second chance and find the Scepter of the Hamster of Darkness, before his evil Uncle Lapin. The Scepter will give immense power to its holder. If Lapin gets hold of it, he will be unstoppable. Accompanied by his faithful servant Abe, a sarcastic turtle, and Meg, a martial arts expert skunk, he sets of on an epic and initiatory quest.",
    popularity: 371.312,
    poster_path: "/2v6f1EqTo4FUxVT9MDXpF6158AX.jpg",
    release_date: "2022-02-16",
    title: "Chickenhare and the Hamster of Darkness",
    video: false,
    vote_average: 7.5,
    vote_count: 171,
  },
  {
    adult: false,
    imgURL: "/n4Iy2cE52WsTKeNtuSD7vgu2qwf.jpg",
    genre_ids: [53],
    id: 985939,
    original_language: "en",
    original_title: "Fall",
    overview:
      "For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights.",
    popularity: 321.095,
    poster_path: "/v28T5F1IygM8vXWZIycfNEm3xcL.jpg",
    release_date: "2022-08-11",
    title: "Fall",
    video: false,
    vote_average: 7.8,
    vote_count: 5,
  },
  {
    adult: false,
    imgURL: "/i9BtOklh2txI78wNSTNjoAZ6Fvj.jpg",
    genre_ids: [35, 10751],
    id: 975120,
    original_language: "es",
    original_title: "Padre no hay mas que Uno 3",
    overview:
      "Christmas is coming. The children accidentally break a Nativity scene figurine from their father's collection and must by all means get an equal one, the problem is that it is a unique antique piece. Sara, the eldest daughter breaks up with her boyfriend, Ocho, who will try to recover her favors with the help of her father-in-law, Javier. Precisely Javier's father-in-law, Marisa's father, will be welcomed into the family home to spend the holidays after her recent separation, which will not leave Javier's mother, Milagros, indifferent. Rocío, the folklore of the family, who has been playing the Virgin for several Christmases, is relegated this year to playing the shepherdess, something that her father, Javier, is not willing to assume.",
    popularity: 333.129,
    poster_path: "/bb7mPVCKVPGFM0NTqd5JmqqI4gu.jpg",
    release_date: "2022-07-15",
    title: "Father There Is Only One 3",
    video: false,
    vote_average: 6.6,
    vote_count: 15,
  },
  {
    adult: false,
    imgURL: "/pFwvHAFyPEqtvJEoutPuobLwrNj.jpg",
    genre_ids: [16, 35, 10751],
    id: 778810,
    original_language: "en",
    original_title: "Fireheart",
    overview:
      "The film explores the world of firefighters in 1920s New York City and tells the story of a 16-year-old girl who will have to become a hero in order to save her city.",
    popularity: 300.419,
    poster_path: "/hepwOZWJNUmLzB68gKYEdEJAaD3.jpg",
    release_date: "2022-01-16",
    title: "Fireheart",
    video: false,
    vote_average: 7.6,
    vote_count: 148,
  },
  {
    adult: false,
    imgURL: "/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg",
    genre_ids: [28, 12, 878],
    id: 545611,
    original_language: "en",
    original_title: "Everything Everywhere All at Once",
    overview:
      "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
    popularity: 294.918,
    poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    release_date: "2022-03-24",
    title: "Everything Everywhere All at Once",
    video: false,
    vote_average: 8.3,
    vote_count: 1332,
  },
  {
    adult: false,
    imgURL: "/rfbpgHbotsnB4sopZDIA3EhPecQ.jpg",
    genre_ids: [35, 28],
    id: 746333,
    original_language: "fr",
    original_title: "Super-héros malgré lui",
    overview:
      "Struggling actor Cedric seems doomed to lead the life of a loser. He's broke and his girlfriend has dumped him. Even his own father, sister and best buddies have lost faith in his ability to do anything worthwhile. Then finally, he gets a lead role: the superhero “Badman“. A chance to pull himself out of an endless downward spiral and gain his father's respect. But fate strikes again! Rushing off the set in full costume, Cedric has a car accident, loses his memory, and wakes up convinced he really is a superhero on mission! Confronted with real-life adventure and danger, his true nature is put to the test. Does he have what it takes to tackle the forces of evil, defend the weakest among us and beat the bad guys? But you can't just decide to be a hero, let alone a superhero... especially someone like Cedric!",
    popularity: 244.975,
    poster_path: "/Aie2kiYOUgZeakpshM2N64PKof1.jpg",
    release_date: "2022-02-02",
    title: "Superwho?",
    video: false,
    vote_average: 6.2,
    vote_count: 199,
  },
  {
    adult: false,
    imgURL: "/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg",
    genre_ids: [27, 9648, 878, 53],
    id: 762504,
    original_language: "en",
    original_title: "Nope",
    overview:
      "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
    popularity: 393.319,
    poster_path: "/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
    release_date: "2022-07-20",
    title: "Nope",
    video: false,
    vote_average: 7.1,
    vote_count: 279,
  },
  {
    adult: false,
    imgURL: "/hcNM0HjfPonIzOVy6LVTDBXSfMq.jpg",
    genre_ids: [28, 53, 80],
    id: 864116,
    original_language: "en",
    original_title: "A Day to Die",
    overview:
      "A disgraced parole officer is indebted to a local gang leader and forced to pull off a series of dangerous drug heists within twelve hours in order to pay the $2 million dollars he owes, rescue his kidnapped pregnant wife, and settle a score with the city's corrupt police chief, who is working with the gang leader and double-crossed him years ago.",
    popularity: 275.089,
    poster_path: "/8Kce1utfytAG5m1PbtVoDzmDZJH.jpg",
    release_date: "2022-03-04",
    title: "A Day to Die",
    video: false,
    vote_average: 6.3,
    vote_count: 131,
  },
  {
    adult: false,
    imgURL: "/yyZgG4VXtcwYKIR8n89OOhFpWRK.jpg",
    genre_ids: [35, 10749, 18],
    id: 1003995,
    original_language: "es",
    original_title: "Enfermo Amor",
    overview: "",
    popularity: 248.005,
    poster_path: "/poYR8Z9jzOPN1rOCSTVk0ioGQtz.jpg",
    release_date: "2022-07-27",
    title: "Enfermo Amor",
    video: false,
    vote_average: 7.3,
    vote_count: 23,
  },
  {
    adult: false,
    imgURL: "/2tVdN2eWsdTegTDuC0miHwGb31E.jpg",
    genre_ids: [18, 12, 53],
    id: 895953,
    original_language: "es",
    original_title: "La cima",
    overview:
      "Mateo undertakes the ascent of Annapurna, the most dangerous mountain on the planet, in order to reach the summit and thus fulfill an old promise.",
    popularity: 211.143,
    poster_path: "/q72KLwwghNn79OS9Gi3J0f5Rki.jpg",
    release_date: "2022-03-25",
    title: "Beyond the Summit",
    video: false,
    vote_average: 6,
    vote_count: 5,
  },
  {
    adult: false,
    imgURL: "/pnZ9NMxRqbcJ2dPNROIoregruv5.jpg",
    genre_ids: [28, 80, 53],
    id: 753232,
    original_language: "en",
    original_title: "The Commando",
    overview:
      "An elite DEA agent returns home after a failed mission when his family makes an unexpected discovery in their house – a stash of money worth $3 million. They soon face the danger and threat of a newly released criminal and his crew, who will do whatever it takes to retrieve the money, including kidnap the agent’s daughters. Stakes are high and lives are at risk in this head-to-head battle as the agent stops at nothing to protect his family against the money-hungry criminals.",
    popularity: 225.473,
    poster_path: "/mn1GYIQ1tvFuuu0YBNZBvrHyrkO.jpg",
    release_date: "2022-01-07",
    title: "The Commando",
    video: false,
    vote_average: 6.2,
    vote_count: 84,
  },
]
